export const datasetList = [
    {title: 'Future Heatwaves'},
    {title: 'Median Tract Income'},
    {title: 'Median County Income'},
    {title: 'National Risk Index'},
    {title: 'Public Schools'},
    {title: 'Flood Zones'},
    {title: 'Electrical Substations'},
    {title: 'Hospitals'},
    {title: 'Public Schools'},
    {title: 'Median Tract Race'},
    {title: 'Median County Race'},
    {title: 'Fire Stations'},
    {title: 'Urgent Care Facilities'},
    {title: 'Power Plants'},
    {title: 'Electrical Transmission Lines'},
    {title: 'Natural Gas Pipelines'},
    {title: 'Surface Water'},
    {title: 'Climate & Atmospheric'},
    {title: 'Air Quality Index'},
    {title: 'US Census'},
    {title: 'Dams'},
    {title: 'SVI'},
];